version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15
    steps:
      - checkout
      - run:
          name: Install Pytest
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -U pytest
            venv/bin/python -m pytest test_script.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
