version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.7
    steps:
      - checkout
      - run:
          name: Install Dependencies and Test
          command: |
            virtualenv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
            make test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build